apiVersion: v1
kind: Service
metadata:
  name: echo-frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: tcp-echo-frontend
    port: 80
    targetPort: 8080
  selector:
    app: echo-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-frontend
      version: v1
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      name: echo-frontend
      labels:
        app: echo-frontend
        version: v1
    spec:
      containers:
      - image: xzhu0027/echo-frontend-grpc-proxyless
        imagePullPolicy: Always
        name: echo-frontend-grpc-proxyless
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  clusterIP: 10.96.77.76
  ports:
  - name: grpc-echo-server
    port: 9000
    targetPort: 9000
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
      version: v1
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      name: echo-server-v1
      labels:
        app: echo-server
        version: v1
    spec:
      containers:
      - image: xzhu0027/echo-server-v1-grpc-proxyless
        imagePullPolicy: Always
        name: echo-server-v1-grpc-proxyless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
      version: v2
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      name: echo-server-v2
      labels:
        app: echo-server
        version: v2
    spec:
      containers:
      - image: xzhu0027/echo-server-v2-grpc-proxyless
        imagePullPolicy: Always
        name: echo-server-v2-grpc-proxyless
---     